// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Ny62st9a0he3_7uZ9HD1wxwBtZMZsaM',
    appId: '1:748192528786:android:a3d8c9943982cb47a8e94b',
    messagingSenderId: '748192528786',
    projectId: 'yoga-scheduling-app-3198f',
    storageBucket: 'yoga-scheduling-app-3198f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskZk_O7lq7jeu3LAf50o-2IwA54MZTz8',
    appId: '1:748192528786:ios:2caac119a42ea798a8e94b',
    messagingSenderId: '748192528786',
    projectId: 'yoga-scheduling-app-3198f',
    storageBucket: 'yoga-scheduling-app-3198f.firebasestorage.app',
    androidClientId: '748192528786-gvjuijmgeuhuj7k01oecjf913a1aiffg.apps.googleusercontent.com',
    iosClientId: '748192528786-gh9gt2l496cfnh84gno60bobihgsff9d.apps.googleusercontent.com',
    iosBundleId: 'com.riftlabs.malahariyoga',
  );
}
