// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhFI9xp06gepkeQzlujPJdwS9swatvUCY',
    appId: '1:748192528786:android:dca82548c993faf6a8e94b',
    messagingSenderId: '748192528786',
    projectId: 'yoga-scheduling-app-3198f',
    storageBucket: 'yoga-scheduling-app-3198f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskZk_O7lq7jeu3LAf50o-2IwA54MZTz8',
    appId: '1:748192528786:ios:5c8d2e37921a2faea8e94b',
    messagingSenderId: '748192528786',
    projectId: 'yoga-scheduling-app-3198f',
    storageBucket: 'yoga-scheduling-app-3198f.firebasestorage.app',
    androidClientId: '748192528786-e87urm54u5eaj4uvtinkcqr387tf72ak.apps.googleusercontent.com',
    iosClientId: '748192528786-h6cf1haees0l7ajr42tbqdb16ojefblg.apps.googleusercontent.com',
    iosBundleId: 'com.riftlabs.malahariyoga',
  );

}